<?xml version="1.0"?>
<package format="2">
  <name>multiaudio_transmit</name>
  <version>2.0.0</version>
  <description>Operator Audio Control and Routing</description>
  <maintainer email="contact@cjt-robotics.de">CJT-Robotics</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>rospy</depend>
  <depend>rqt_gui</depend>
  <depend>rqt_gui_py</depend>
  <depend>std_msgs</depend>
  <depend>audio_common_msgs</depend>
  <depend>audio_capture</depend>
  <depend>audio_play</depend>

  <export>
    <rqt_gui plugin="${prefix}/plugin.xml"/>
  </export>
</package>